name: android

on:
  release:
    types: [prereleased, released, published]
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - main
      - feature/*
  push:
    branches:
      - main
      - feature/*
  schedule:
    # GMT timezone.
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  android-arm64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: android-arm64
      nightly: ${{ github.event.inputs.nightly }}
      keep_artifacts: cobalt.apk
  android-x86:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: android-x86
      nightly: ${{ github.event.inputs.nightly }}
      keep_artifacts: cobalt.apk
  android-arm:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: android-arm
      nightly: ${{ github.event.inputs.nightly }}
      keep_artifacts: cobalt.apk

  final_android_job:
    runs-on: ubuntu-latest
    needs: [ android-arm, android-arm64, android-x86 ]
    permissions:
      actions: write
    # v4 is unreliable
    # https://github.com/actions/download-artifact/issues/249
    steps:
      - name: Download the gold arm thing
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: android-arm-gold
          path: arm-gold
      - name: Download the qa arm thing
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: android-arm-qa
          path: arm-qa
      - name: Download the gold arm64 thing
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: android-arm64-gold
          path: arm64-gold
      - name: Download the qa arm64 thing
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: android-arm64-gold
          path: arm64-qa
      - name: Download the gold x86 thing
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: android-x86-gold
          path: x86-gold
      - name: Download the qa x86 thing
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: android-x86-gold
          path: x86-qa
      - name: 'Upload Android APKs'
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4
        with:
          name: Android APKs
          path: ./*
          retention-days: 90
          compression-level: 0 # We expect kept artifacts to be already compressed
          if-no-files-found: error
      - name: 'Delete intermediates'
        uses: geekyeggo/delete-artifact@9d15d164b1dcd538ff1b1a2984bc2c0240986c3b # v4.0.0
        with:
          token: ${{ github.token }}
          name: android-arm-qa
          failOnError: true
      - name: Upload the APKs to a release
        if: ${{ github.event_name == 'release' }}
        uses: skx/github-action-publish-binaries@b9ca5643b2f1d7371a6cba7f35333f1461bbc703 # release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: |
            .
